name: Build Next.js web application
on:
  release:
    types:
      - created
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rayding2012/build_test
          tags: ${{ github.run_number }}, latest
